### ISSUE TITLE
GPS data out problem

### ISSUE THREAD

**Issue by RySaw** [BYU-Spacecraft-Group/TriSeptRaspberryPi#3]
When the gps doesn't have a fix, it correctly outputs dashes for all data points. When the gps does have a fix, and is outputting data to the csv file, it completely skips over the number of sattelites data point, causing all remaining data points in that line of the csv file to be shifted to the left.

**Comment by tylermnielsen** [comment]
Pretty sure I've solved this one, you'll have to check when it can get GPS signal. The problem was that in transferring the GPS code over to totalCombined.py the reading of gps.fix_quality was labelled satellites and the reading of gps.satellites was lost, leading to less columns being saved than expected. I straightened them out so it should be good now.
